

-- Drop tables
DROP TABLE IF EXISTS Dog CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS Cat CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS ADOPTION CASCADE CONSTRAINTS;  
DROP TABLE IF EXISTS PET;
DROP TABLE IF EXISTS OWNER;
DROP TABLE IF EXISTS VETERINARIAN;
DROP TABLE IF EXISTS BREED;
DROP TABLE IF EXISTS LOCATION;
